spring:
  jpa:
#    show-sql: true
    open-in-view: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  liquibase:
    change-log: classpath:/db/changelog/changelod.yml

  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none