spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  liquibase:
    enabled: false
  jackson.visibility:
    field: any
    getter: none
    setter: none
    is-getter: none